### ISSUE TITLE
alpaca image does not seem to honor ALPACA_ACTIVEMQ_URL

### ISSUE THREAD

**Issue by derekbelrose** [jhu-idc/idcApp-k8s#8]
```2021-01-17T04:40:31Z alpaca-6957465549-68rc5 confd[386]: DEBUG Key Map: map[string]string{"/alpaca/activemq/url":"tcp://activemq:61616", "/alpaca/activemq/password":"password", "/alpaca/karaf/admin/password":"password"}
2021-01-17T04:40:31Z alpaca-6957465549-68rc5 confd[386]: DEBUG Got the following map from store: map[/alpaca/activemq/url:tcp://activemq:61616 /alpaca/activemq/password:password /alpaca/karaf/admin/password:password]
```
```
2021-01-17 04:40:39,613 | WARN  | ActiveMQ Task-1  | FailoverTransport                | 53 - org.apache.activemq.activemq-osgi - 5.15.0 | Failed to connect to [tcp://localhost:61616] after: 10 attempt(s) continuing to retry.
2021-01-17 04:41:34,082 | WARN  | FelixStartLevel  | BlueprintEventDispatcher         | 12 - org.apache.aries.blueprint.core - 1.7.1 | Listener timed out, will be ignored
java.util.concurrent.TimeoutException
	at java.util.concurrent.AbstractExecutorService.doInvokeAny(AbstractExecutorService.java:184)[:1.8.0_252]
	at java.util.concurrent.AbstractExecutorService.invokeAny(AbstractExecutorService.java:225)[:1.8.0_252]
	at org.apache.aries.blueprint.utils.threading.ScheduledExecutorServiceWrapper$4.call(ScheduledExecutorServiceWrapper.java:184)[12:org.apache.aries.blueprint.core:1.7.1]
	at org.apache.aries.blueprint.utils.threading.ScheduledExecutorServiceWrapper$15.call(ScheduledExecutorServiceWrapper.java:452)[12:org.apache.aries.blueprint.core:1.7.1]
	at org.apache.aries.blueprint.utils.threading.RWLock.runReadOperation(RWLock.java:35)[12:org.apache.aries.blueprint.core:1.7.1]
	at org.apache.aries.blueprint.utils.threading.ScheduledExecutorServiceWrapper.runUnlessShutdown(ScheduledExecutorServiceWrapper.java:447)[12:org.apache.aries.blueprint.core:1.7.1]
	at org.apache.aries.blueprint.utils.threading.ScheduledExecutorServiceWrapper.invokeAny(ScheduledExecutorServiceWrapper.java:178)[12:org.apache.aries.blueprint.core:1.7.1]
	at org.apache.aries.blueprint.container.BlueprintEventDispatcher.callListener(BlueprintEventDispatcher.java:199)[12:org.apache.aries.blueprint.core:1.7.1]
	at org.apache.aries.blueprint.container.BlueprintEventDispatcher.callListeners(BlueprintEventDispatcher.java:189)[12:org.apache.aries.blueprint.core:1.7.1]
	at org.apache.aries.blueprint.container.BlueprintEventDispatcher.blueprintEvent(BlueprintEventDispatcher.java:140)[12:org.apache.aries.blueprint.core:1.7.1]
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:424)[12:org.apache.aries.blueprint.core:1.7.1]
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:276)[12:org.apache.aries.blueprint.core:1.7.1]
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:300)[12:org.apache.aries.blueprint.core:1.7.1]
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:269)[12:org.apache.aries.blueprint.core:1.7.1]
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:265)[12:org.apache.aries.blueprint.core:1.7.1]
	at org.apache.aries.blueprint.container.BlueprintExtender.modifiedBundle(BlueprintExtender.java:255)[12:org.apache.aries.blueprint.core:1.7.1]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:500)[21:org.apache.aries.util:1.1.1]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:433)[21:org.apache.aries.util:1.1.1]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$AbstractTracked.track(BundleHookBundleTracker.java:725)[21:org.apache.aries.util:1.1.1]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.bundleChanged(BundleHookBundleTracker.java:463)[21:org.apache.aries.util:1.1.1]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$BundleEventHook.event(BundleHookBundleTracker.java:422)[21:org.apache.aries.util:1.1.1]
	at org.apache.felix.framework.util.SecureAction.invokeBundleEventHook(SecureAction.java:1179)[org.apache.felix.framework-5.6.1.jar:]
	at org.apache.felix.framework.EventDispatcher.createWhitelistFromHooks(EventDispatcher.java:730)[org.apache.felix.framework-5.6.1.jar:]
	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:485)[org.apache.felix.framework-5.6.1.jar:]
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4541)[org.apache.felix.framework-5.6.1.jar:]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2172)[org.apache.felix.framework-5.6.1.jar:]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)[org.apache.felix.framework-5.6.1.jar:]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)[org.apache.felix.framework-5.6.1.jar:]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_252]
```

**Comment by jhujasonw** [comment]
I spoke to @birkland about this while I was debugging some derivative issues, this message is apparently a non-error message and doesn't effect alpaca.  It's an artifact that the devs have not been able to trace down and remove.
